### ISSUE TITLE
v1.4 Release

### ISSUE THREAD

**Issue by acrylic-style** [rht0910/PluginManager#48]
**Changes (v1.4)**
----
* **Changed Depends: Required 'TomeitoLib'**
* Fixed version checker bug.
* Load plugin is now async.
* Log(class) removed
* Added: TabComplete, Async LoadPlugin
* Source code clean-up [ PluginUtils#loadPlugin() ]

**Current issues:**
----
* <s>All except en_US: Delayed version(Display only. Work's great!)</s>
*This problem is resolved.*

**Note:**
----
* For Translators: Translation as far as possible.
* Manager class is maybe not used.
**Version number changed from 1.3.1 to 1.4**
* New master branch of release is pull request(#49) ... Merged.

**Comment by rht0910** [comment]
#49

**Comment by acrylic-style** [comment]
Released: #50 .
This issue has closed.
